# Compilazione

FROM openjdk:17 as builder
WORKDIR /app

COPY .mvn .mvn
COPY mvnw .
COPY pom.xml .
RUN chmod -R 777 *
RUN ./mvnw -B dependency:go-offline                          

COPY src src
RUN ./mvnw -B package                                        

# Esecuzione

FROM openjdk:17
COPY --from=builder /app/target/seecity-0.0.1-SNAPSHOT.jar ./city.jar       
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "city.jar"]
